MovieApp/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

MovieApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }


    }
}

MovieApp/Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
    }
}

MovieApp/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public  static class Repository
    {
        private static List<Movie> _movies = null;
        static Repository()
        
        {
            _movies = new List<Movie>()
            {
                new Movie(){Id=1,
                    Name ="Captain America",
                    ShortDescription="Captain America",
                    Description ="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
                    ImageUrl ="3.jpg"
                },
                new Movie(){Id=2, Name="Hulk",
                    ShortDescription ="Hulk",
                    Description ="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
                    ImageUrl ="2.jpg"},
                new Movie(){Id=3,
                    Name ="Iron Man",
                    ShortDescription ="Iron Man",
                    Description ="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
                    ImageUrl ="3.jpg"},
                new Movie(){Id=4,
                    Name ="Hawkeye",
                    ShortDescription ="Hawkaye",
                    Description =" <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
                    ImageUrl ="4.jpg"},
                new Movie(){Id=5,
                    Name ="Black Widow",
                    ShortDescription ="Black Widow",
                    Description ="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
                    ImageUrl ="5.jpg"}

            };
        }
        public static List<Movie> Movies
        {
            get { return _movies; }
        }
        public static void AddMovie(Movie entity)
        {
            _movies.Add(entity);
        }
        public static Movie GetById(int id)
        {
            return _movies.FirstOrDefault(i => i.Id == id);
        }
    }
}

MovieApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;
            if (id!=null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();

            }


            return View(movies);
        }
        public ActionResult Details(int id)
        {
            //MovieCategoryModel model = new MovieCategoryModel();
            //model.Categories = CategoryRepository.Categories;
            //model.Movie = MovieRepository.GetById(id);
            return View(MovieRepository.GetById(id));
        }
        public ActionResult Contact()
        {
            return View();
        }

    }
}

MovieApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        public IActionResult List()
        {
            return View();
        }
    }
}

MovieApp/ViewCompanents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.ViewCompanents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString()=="Index")
            {
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            }
            
            return View(CategoryRepository.Categories);
        }
    }
}

MovieApp/Views/Home/Contact.cshtml
<h1>Home/contact</h1>

MovieApp/Views/Home/Details.cshtml
@model Movie


    <div class="row">
        <div class="col-md-3">
            @*@Html.Partial("_menu",Model.Categories)*@
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class=" col-md-9">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row no-gutter">
                        <div class="col-md-4">
                            <img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img" />
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">
                                <a href="/home/details/@Model.Id">@Model.Name </a>
                            </h5>
                            <p class="card-text">  @Html.Raw(Model.Description) </p>
                            <p class="card-text">
                                <small class="text-muted">3 days ago</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

MovieApp/Views/Home/Index.cshtml
@model IEnumerable<Movie>


<div class="row">
    <div class="col-md-3">
         @*@Html.Partial("_menu",Model.Categories)*@

        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
         @Html.Partial("_movies",Model) 
   

    </div>
</div>

MovieApp/Views/Home/_movies.cshtml
@model  IEnumerable<Movie>
@foreach (var item in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/img/@item.ImageUrl" alt="@item.Description" class="card-img" />

            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="/home/details/@item.Id">@item.Name </a>
                       
                     
                    </h5>
                    <p class="card-text">  @item.ShortDescription </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>

            </div>

        </div>

    </div>
}

MovieApp/Views/Movie/Details.cshtml
<h1>Movie/Details</h1>

MovieApp/Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

MovieApp/Views/Movie/List.cshtml
<h1>Movie/List</h1>

MovieApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>


    <div class="list-group">
        <a href="/"
           class="list-group-item list-group-item-action">
            Tüm Kategoriler
        </a>

        @foreach (var i in Model)
        {
            <a asp-controller="Home" asp-action="Index" asp-route-id="@i.Id"
               class="list-group-item list-group-item-action action @(ViewBag.SelectedCategory==i.Id.ToString()?"active":"")">@i.Name</a>
        }



    </div>

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>

    <meta name="viewport" content="width=device-width" />
    <link href="/modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Style.css" rel="stylesheet" />
    <title>Movie App</title>
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>




</body>
</html>

MovieApp/Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Place footer content here.
        </span>
    </div>
</div>

MovieApp/Views/Shared/_menu.cshtml
@model  IEnumerable<Category>


    <div class="list-group">

        @foreach (var i in Model)
        {
            <a href="#" class="list-group-item list-group-item-adction">@i.Name</a>
        }



    </div>

MovieApp/Views/Shared/_navbar.cshtml
<div class="navbar navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>       

MovieApp/Views/Shared/menu.cshtml
<div class="list-group">

    <a href="#" class="list.group-item list-group-item-action active">Link Item 1</a>
    <a href="#" class="list.group-item list-group-item-action ">Link Item 2</a>
    <a href="#" class="list.group-item list-group-item-action ">Link Item 3</a>
    <a href="#" class="list.group-item list-group-item-action ">Link Item 4</a>
    <a href="#" class="list.group-item list-group-item-action active">Link Item 5</a>

</div>